version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
    groups:
      npm-package-updates:
        applies-to: version-updates
        patterns:
          - "package-lock.json"
          - "package.json"
