run-name: '🚀 Publish'

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

defaults:
  run:
    shell: bash

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    environment: npm-publish-public

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm

      - name: NPM Install
        run: npm install

      - name: Compile TypeScript
        run: npx tsc

      - name: Publish to NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" >> ~/.npmrc
          npm publish ${{ vars.NPM_PUBLISH_ACCESS }}

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create \
            ${{ github.ref_name }} \
            --generate-notes \
            --latest=true \
            --title "${{ github.ref_name }}" \
            --verify-tag
